services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    command: ['-config.file=/etc/loki/local-config.yaml']
    ports:
      - '3100:3100'
    networks:
      - booking-net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
    networks:
      - booking-net

  tempo:
    container_name: tempo
    image: grafana/tempo:2.2.2
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - '3200:3200' # Tempo
      - '9411:9411' # Zipkin
    networks:
      - booking-net

  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - '3000:3000'
    networks:
      - booking-net

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    ports:
      - '9100:9100'
    networks:
      - booking-net

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8081:8080'
    networks:
      - booking-net

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - booking-net
