global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'monitoring'
    static_configs:
      - targets: ['node-exporter:9100', 'cadvisor:8080', 'redis-exporter:9121']

  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['server:8888']
