server:
  port: 8888
# Swagger config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  application:
    name: ticket-booking
  # Database config
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA config
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: never
      schema-locations: classpath:db/migration
      data-locations: classpath:db/migration
  # Config Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
    baseline-on-migrate: true
  # Config Redis
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
  cache:
    type: redis
  # Mail Properties
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: d44afe38e75431
    password: 004bd628e2ec80
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            jdbc: debug

  #Config VNPay
payment:
  VNPay:
    url: ${VNPAY_URL}
    tmnCode: ${VNPAY_TMN_CODE}
    secretKey: ${VNPAY_SECRET_KEY}
    returnUrl: ${VNPAY_RETURN_URL}
    version: ${VNPAY_VERSION}
    command: ${VNPAY_COMMAND}
    orderType: ${VNPAY_ORDER_TYPE}
  #Config JWT
dawn:
  app:
    jwtCookieName: dawn-jwt
    jwtRefreshCookieName: dawn-jwt-refresh
    jwtSecret: =====================DawnBreaker===========================
    #      jwtExpirationsMs: 86400000
    #      jwtRefreshExpirationsMs: 86400000
    ## For test
    jwtExpirationsMs: 60000
    jwtRefreshExpirationsMs: 120000
    setup:
      admin:
        username: ${ADMIN_USERNAME}
        email: ${ADMIN_EMAIL}
        password: ${ADMIN_PASSWORD}