spring:
  application:
    name: dawn-ai
langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_API_KEY}
      model-name: ${GEMINI_API_MODEL}
      log-requests-and-responses: true
      temperature: 0.7
      timeout: 60s
      max-retries: 0
